version: '3.8'

networks:

  public:
    external: true

volumes:

  traefik: {}

services:

  traefik:
    image: traefik:v2.4
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik:/certificates
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `public`)
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=${EMAIL}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
    deploy:
      placement:
        constraints:
          - node.labels.traefik == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.public-http.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.public-http.entrypoints=http
        - traefik.http.routers.public-http.middlewares=https-redirect
        - traefik.http.routers.public-https.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.public-https.entrypoints=https
        - traefik.http.routers.public-https.tls=true
        - traefik.http.routers.public-https.service=api@internal
        - traefik.http.routers.public-https.tls.certresolver=le
        - traefik.http.services.public.loadbalancer.server.port=8080
