version: '3.8'

networks:

  public:
    external: true

volumes:

services:

  transmission:
    image: haugene/transmission-openvpn:3.7.1
    container_name: transmission
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TRANSMISSION_DOWNLOADS}:/downloads
      - ${TRANSMISSION_DOWNLOADS_INCOMPLETE}:/incomplete-downloads
      - ${TRANSMISSION_WATCH}:/data/watch
    environment:
      - PUID
      - PGID
      - TZ
      - UMASK_SET: "18"
      - OPENVPN_PROVIDER
      - OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60"
      - LOCAL_NETWORK: "10.0.0.0/8"
      - CREATE_TUN_DEVICE: "true"
      - TRANSMISSION_UTP_ENABLED: "false"
      - TRANSMISSION_DOWNLOAD_DIR
      - TRANSMISSION_INCOMPLETE_DIR
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      - TRANSMISSION_WEB_UI: "transmission-web-control"

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${SABNZBD_CONFIG}:/config
      - ${SABNZBD_DOWNLOADS}:/downloads
      - ${READARR_DOWNLOADS_INCOMPLETE}:/incomplete-downloads
