version: '3.8'

networks:

  public:
    external: true

volumes:

services:

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - TZ
      - PLEX_UID: ${PUID}
      - PLEX_GID: ${PGID}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${PLEX_CONFIG}:/config
      - ${PLEX_TRANSCODE}:/transcode
      - ${PLEX_DATA}:/data
