libraries:
  Movies:
    metadata_path:
      - file: config/Movies.yaml
  TV Shows:
    metadata_path:
      - file: config/TV-Shows.yaml
  Anime:
    metadata_path:
      - file: config/Anime.yaml

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  sync_mode: append
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: true
  run_again_delay: 2
  released_missing_only: false
  create_asset_folders: false
  missing_only_released: false
  collection_minimum: 1
  delete_below_minimum: true
  tvdb_language: eng

plex:
  url: https://plex.home
  token: ################################
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false

tmdb:
  apikey: ################################
  language: en

tautulli:
  url: https://tautulli.home
  apikey: L3X4qIJn6xRExTCDa0jtV7yCnwgU0Hq_

radarr:
  url: https://radarr.home
  token: acbcaa6ef63d43a98ebc0e4c64dc5586
  add: false
  root_folder_path: S:/Movies
  monitor: true
  availability: announced
  quality_profile: HD-1080p
  tag:
  search: false

sonarr:
  url: https://sonarr.home
  token: 67c0c837c1b54bdfb36d070377c0011d
  add: false
  root_folder_path: 'S:/TV Shows'
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false

trakt:
  client_id: ################################
  client_secret: ################################
  authorization: ################################
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope: public
    created_at:
