collections:
  ######################################################
  #                Dynamic Collections                 #
  ######################################################

  # TMDb Popular:
  #   tmdb_popular: 30
  #   sync_mode: sync
  #   sort_title: $000

  ######################################################
  #               Genre/Year Collections               #
  ######################################################

  Family:
    plex_search:
      genre: Family
    summary: A collection of family films.
    sort_title: '*000'
    collection_order: alpha
    collection_mode: default
  Action:
    plex_search:
      genre: Action, Action/Adventure
    summary: A collection of action films.
    sort_title: '*001'
    collection_order: alpha
    collection_mode: default
  Comedy:
    plex_search:
      genres: Comedy
    summary: A collection of comedy films.
    sort_title: '*002'
    collection_order: alpha
    collection_mode: default
  Science Fiction:
    plex_search:
      genres: Sci-Fi
    summary: A collection of sci-fi films.
    sort_title: '*003'
    collection_order: alpha
    collection_mode: default
  1970s:
    plex_search:
      year: 1970-1979
    summary: A collection of movies released in the 1970s
    sort_title: '*004'
    collection_mode: default
  1980s:
    plex_search:
      year: 1980-1999
    summary: A collection of movies released in the 1980s
    sort_title: '*005'
    collection_mode: default
  1990s:
    plex_search:
      year: 1990-1999
    summary: A collection of movies released in the 1990s
    sort_title: '*006'
    collection_mode: default
  2000s:
    plex_search:
      year: 2000-2009
    summary: A collection of movies released in the 2000s
    sort_title: '*007'
    collection_mode: default
  2010s:
    plex_search:
      year: 2010-2019
    summary: A collection of movies released in the 2010s
    sort_title: '*008'
    collection_mode: default

  ######################################################
  #               Universes Collections                #
  ######################################################

  Pixar:
    imdb_list: https://www.imdb.com/list/ls087911008/
    summary: A collection of Pixar movies
    sort_title: '+000'
    content_rating: G
    collection_order: release
    collection_mode: default
  Marvel Cinematic Universe:
    imdb_list: https://www.imdb.com/list/ls066946827/
    summary: A collection of all MCU movies.
    sort_title: '+001'
    collection_order: release
    collection_mode: default
  Walt Disney Animation Studios:
    imdb_list: https://www.imdb.com/search/title/?companies=co0074039&count=250
    summary: A collection of Disney Animation movies.
    sort_title: '+002'
    collection_order: alpha
    collection_mode: default
  Wizarding World:
    tmdb_list: https://www.themoviedb.org/list/94773
    summary: A collection of all the Wizarding World movies.
    sort_title: '+003'
    collection_order: release
    collection_mode: default
  Star Wars:
    tmdb_collection: https://www.themoviedb.org/collection/10-star-wars-collection
    tmdb_summary: https://www.themoviedb.org/collection/10-star-wars-collection
    sort_title: '+004'
    collection_order: release
    collection_mode: default
  Spider-Man:
    imdb_list: https://www.imdb.com/list/ls049852613/
    summary: A collection of all Spider-Man movies.
    sort_title: '+005'
    collection_order: release
    collection_mode: default
  Middle Earth:
    tmdb_collection:
      - 119
      - 121938
    summary: A collection of all J.R.R. Tolkien's movies.
    sort_title: '+006'
    collection_order: release
    collection_mode: default

  ######################################################
  #               Directors Collections                #
  ######################################################

  Christopher Nolan:
    plex_search:
      directors: Christopher Nolan
    summary: A collection of Christopher Nolan's movies.
    sort_title: '.000'
    collection_order: release
    collection_mode: default
  Martin Scorsese:
    plex_search:
      directors: Martin Scorsese
    summary: A collection of Martin Scorsese's movies.
    sort_title: '.001'
    collection_order: release
    collection_mode: default
  Quentin Tarantino:
    plex_search:
      directors: Quentin Tarantino
    summary: A collection of Quentin Tarantino's movies.
    sort_title: '.002'
    collection_order: release
    collection_mode: default

  ######################################################
  #                 List Collections                   #
  ######################################################

  Chris Stuckmann Hilariocity:
    imdb_list: https://www.imdb.com/list/ls089509838/
    summary: Chris Stuckmann reviews cinematic abominations so awful, he believes them to be hilarious.
    sort_title: '/000'
    collection_order: alpha
    collection_mode: default
  Best Picture Winners:
    imdb_list: https://www.imdb.com/list/ls062667125/
    summary: A collection of all Oscar winners.
    sort_title: '/001'
    collection_order: alpha
    #schedule: monthly(1), monthly(15)
    collection_mode: default
    sync_mode: sync
  Best Picture Nominees:
    imdb_list: https://www.imdb.com/list/ls009487211/
    summary: A collection of all Oscar nominees.
    sort_title: '/002'
    collection_order: alpha
    #schedule: monthly(1), monthly(15)
    collection_mode: default
    sync_mode: sync
  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=250
    sync_mode: sync
    sort_title: '/003'
    collection_order: alpha
    #schedule: monthly(1), monthly(15)
    collection_mode: default
  Reddit Top 250:
    trakt_list: https://trakt.tv/users/jay-greene/lists/reddit-top-250-2019-edition
    summary: A collection of Reddit's Top 250 Movies (2019).
    sort_title: '/004'
    collection_order: alpha
    #schedule: monthly(1), monthly(15)
    collection_mode: default
    sync_mode: sync

  ######################################################
  #                 TMDB Collections                   #
  ######################################################

  Back to the Future:
    tmdb_collection: 264
    tmdb_summary: 264
    collection_mode: hide
  Deadpool:
    tmdb_collection: 448150
    tmdb_summary: 448150
    collection_mode: hide
  Fantastic Beasts:
    tmdb_collection: 435259
    tmdb_summary: 435259
    collection_mode: hide
  The Godfather:
    tmdb_collection: 230
    tmdb_summary: 230
    collection_mode: hide
  Harry Potter:
    tmdb_collection: 1241
    tmdb_summary: 1241
    collection_mode: hide
  John Wick:
    tmdb_collection: 404609
    tmdb_summary: 404609
    collection_mode: hide
  Mission Impossible:
    tmdb_collection: 87359
    tmdb_summary: 87359
    collection_mode: hide
  Pirates of the Caribbean:
    tmdb_collection: 295
    tmdb_summary: 295
    collection_mode: hide
  The Karate Kid:
    tmdb_collection: 8580
    tmdb_summary: 8580
    collection_mode: hide
  MonsterVerse:
    imdb_list: https://www.imdb.com/list/ls060980695/
    summary: A collection of all the MonsterVerse movies.
    collection_mode: hide
  The Dark Knight Collection:
    tmdb_collection: 263
    tmdb_summary: 263
    collection_mode: hide
