# A starter config to use with Trash Updater. Most values are set to "reasonable defaults".
# Update the values below as needed for your instance. You will be required to update the
# API Key and URL for each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://github.com/rcdailey/trash-updater/wiki/Configuration-Reference

# Configuration specific to Sonarr
sonarr:
  - base_url: https://sonarr.home/
    api_key: 67c0c837c1b54bdfb36d070377c0011d
    quality_definition: hybrid
    release_profiles:
      - type: anime
      - type: series

# Configuration specific to Radarr.
radarr:
  - base_url: https://radarr.home/
    api_key: acbcaa6ef63d43a98ebc0e4c64dc5586
    quality_definition:
      type: movie
    delete_old_custom_formats: false
    custom_formats:
      - names:
        - BR-DISK
        - EVO (no WEB-DL)
        - LQ
        - x265 (720/1080p)
        - 3D
